name: Test 3
description: Description for Test 3
title: "Create new issue from template Test 3"
labels: ["Test 1", "Test 2"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your time!
  - type: input
    id: email
    attributes:
      label: Your email
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@wearehackerone.com
    validations:
      required: true
  - type: dropdown
    id: product
    attributes:
      label: Product
      description: What software are you running?
      options:
        - Product 1
        - Product 2
        - Product 3
    validations:
      required: true
